version: '3'

services:
  nginx-rtmp:
    image: alfg/nginx-rtmp
    ports:
      - 1935:1935
      - 80:80
    volumes:
      - ./certs:/opt/certs
      - ./data:/opt/data
      - ./nginx.conf:/opt/nginx/nginx.conf
